import { array } from "@utils";
import { Header } from "components";
import Head from "next/head";
import Link from "next/link";

import mongoClient from "../lib/mongoClient";

export default function Home({ phrases }) {
  return (
    <div className="antialiased text-zinc-500 dark:text-zinc-400 bg-white dark:bg-zinc-900">
      <Head>
        <title>wordd.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="" style={{ minHeight: "calc(100vh - 4rem)" }}>
        <div className="container mx-auto ">
          <div className="mx-auto text-center max-w-5xl py-20">
            <h2 className="text-zinc-900 dark:text-zinc-200 text-2xl md:text-5xl font-bold ">
              İngilizce ifadeleri keşfedin!
            </h2>
            <p className="pt-8">
              İngilizce ifadelerin Türkçe karşıklıklarını öğrenin. İngilizce
              cümle kurmakta zorlanıyorsanız veya kurduğunuz cümlenin doğru olup
              olmadığından emin değilseniz,{" "}
              <Link href="/">
                <a className="font-semibold text-indigo-500 dark:text-indigo-400">
                  wordd.io
                </a>
              </Link>{" "}
              üzerinden arama yaparak benzer cümleleri bulabilirsiniz.
            </p>
          </div>
          <div className="py-4 grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            {array(phrases)?.map((phrase) => (
              <div
                key={phrase?.slug}
                className="py-4 px-4 bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 rounded-lg dark:highlight-white/5"
              >
                <div className="font-bold text-lg">
                  <Link href={`/phrase/${phrase?.slug}`}>
                    <a className="hover:underline">{phrase?.sentence?.en}</a>
                  </Link>
                </div>
                <div className="dark:text-zinc-400 pt-3">
                  {phrase?.sentence?.tr}
                </div>
                <div className="text-sm pt-6 space-x-2">
                  {array(phrase?.tag)?.map((tag) => (
                    <Link href="/" key={tag}>
                      <a className="font-semibold text-indigo-500 dark:text-indigo-400">
                        #{tag}
                      </a>
                    </Link>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    const client = await mongoClient;
    const db = client.db("wordd");
    const collection = db.collection("phrases");
    const phrases = await collection.find({}).toArray();

    return {
      props: {
        phrases: JSON.parse(JSON.stringify(phrases)),
      },
    };
  } catch (error) {
    return {
      props: {
        phrases: [],
      },
    };
  }
}
